### ISSUE TITLE
Link to Image in Blog #2 is Broken

### ISSUE THREAD

**Issue by haimivan** [lilianweng/stock-rnn#10]
For the referring blog post number 2 :
[https://lilianweng.github.io/lil-log/2017/07/22/predict-stock-prices-using-RNN-part-2.html#price-prediction](https://lilianweng.github.io/lil-log/2017/07/22/predict-stock-prices-using-RNN-part-2.html#price-prediction
)
the png picture with the following url is not displayed:

`/lil-log/assets/images/rnn_embedding_result.png`
(Xpath: `/html/body/main/div/article/div[1]/p[34]/img` )

Text before broken link:
_With a small input_size, the model does not need to worry about the long-term growth curve. Once we increase input_size, the prediction would be much harder._

**Comment by lilianweng** [comment]
Just updated!

**Comment by haimivan** [comment]
thanks
