### ISSUE TITLE
how to predicate a single price for tomorrow?

### ISSUE THREAD

**Issue by johndpope** [lilianweng/stock-rnn#4]
awesome job on this - very clean.

but how to predicate a single price for tomorrow?
eg. for tesla stocks?
I get I can easily download and train from history - 
https://finance.yahoo.com/quote/TSLA/history?p=TSLA

but where can I tell it tomorrow's date?

**Comment by lilianweng** [comment]
If you use the last chuck of available prices, which would be up to today, feed it into the model and I would expect the output to be tomorrow price(s).

The model does not know the dates but only the sequences and the order of numbers.

**Comment by plagi** [comment]
How can you feed data in to the model?

**Comment by rishiswethan** [comment]
Where do I see this prediction for tomorrow?

**Comment by CaesarChen1991** [comment]
Same question here.. Having no idea of how to feed new data to the model.

**Comment by johndpope** [comment]
this fibonacci pivot point at $7156 hit the other day - and buyers entered huge orders - triggering rally.
<img width="568" alt="screen shot 2018-03-20 at 10 46 37 am" src="https://user-images.githubusercontent.com/289994/37661807-fc53d804-2c2b-11e8-9d6a-0a60336f37e1.png">

**Comment by cikoned** [comment]
same question here???

**Comment by johndpope** [comment]
just flip a coin / heads it's up / tails it's down.
