### ISSUE TITLE
Embedding configured incorrectly

### ISSUE THREAD

**Issue by ssatia** [lilianweng/stock-rnn#6]
`self. inputs_with_embed` holds the embeddings concatenated with `self.inputs`. However, the embeddings are not being used since the RRN is still using `self.inputs`:

https://github.com/lilianweng/stock-rnn/blob/aa03e93fb0cf55990c2fb64d52902bb98186eed5/model_rnn.py#L102

**Comment by lilianweng** [comment]
You are totally right. The issue has been fixed in commit 084707d :)

Thanks!
